name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

    inputs:

      ContainerTag:
        type: string
        default: ""
        description: Container Tag


jobs:
  Firstjob:
    runs-on: ubuntu-latest
    if: inputs.ContainerTag
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Hello world job
        run: |
          echo "Hello world12"
          echo "Another line"
        shell: bash

  Secondjob:
    needs:
      -  Firstjob
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        run: |
          echo "This is the second job"
        shell: bash

  finishjob:
    needs:
      - Firstjob
      - Secondjob
    runs-on: ubuntu-latest
    steps:
      - name: Third job
        run: |
          echo "My name is ${{ vars.NAME_VARIABLE }}"
          echo "The password is ${{ secrets.PASSWORD }}"
        shell: bash
