name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Hello world job
        run: |
          echo "Hello world12"
          echo "Another line"
        shell: bash

  Secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        run: |
          echo "This is the second job"
        shell: bash

  finishjob:
    runs-on: ubuntu-latest
    steps:
      - name: Third job
        run: |
          echo "My name is ${{ vars.NAME_VARIABLE }}"
          echo "The password is ${{ secrets.NAME_VARIABLE }}"
        shell: bash
