name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      main
  workflow_dispatch:

jobs:
  Firstjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world job
        run: |
          echo "Hello world"
          echo "Another line"
        shell: bash
  Secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: last goodbye
        run: echo "This is the second job"
        shell: bash
  finishjob:
    runs-on: ubuntu-latest
    steps:
      - name: last goodbye
        run: echo "goodbye world"
        shell: bash
        