name: create a comment on new issue
on:
  issues:
    types: [opened]
jobs:
  comment-with_action:
    runs-on: ubuntu-latest
    steps:
      - name: "creating comment on github"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      
