name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy'
        required: true
        default: 'production'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  Firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print-statement
        run: |
          echo "Hello world12"
          echo "Another line"
        shell: bash
